### ISSUE TITLE
Google JamBoard

### ISSUE THREAD

**Issue by Madison-Rutledge** [codyogden/killedbygoogle#1437] opened 2023-09-28 19:21 UTC
Google Jamboard 
Digital cloud synced whiteboard tool
May 2017
Late 2024
App/Service

**Comment by dgw** [comment] 2023-09-28 20:29
Duplicate of #1435

**Comment by slashtab** [comment] 2023-09-29 03:49
This issue is more precise and correct as per the available information. Although it should include **Hardware**.

**Comment by rinkp** [comment] 2023-09-29 19:08
Today's email announcement included December 31, 2024 as end date

> Starting October 1, 2024, you’ll no longer be able to create new or edit existing Jams on any platform, including the web, iOS, and Android. Between October 1, 2024 and December 31, 2024, the app will be placed in “view-only” mode, during which time you can continue to back up your Jam files.

**Closed** 2023-10-07 21:57 UTC
