### ISSUE TITLE
Google now desktop

### ISSUE THREAD

**Issue by kayvonkamyar** [codyogden/killedbygoogle#315] opened 2019-03-28 16:54 UTC
` google now desktop

**When was the product launched? Provide a specific date, if possible.**

**When was the product discontinued? Provide a specific date, if possible.**

**What type of product was it? App, Service, or Hardware?**

**Comment by codyogden** [comment] 2019-03-28 17:24
Duplicate of #314

**Closed by codyogden** 2019-03-28 17:24 UTC
