### ISSUE TITLE
YouTube for Nintendo Wii (a bit late, but needs to be included)

### ISSUE THREAD

**Issue by seanpm2001** [codyogden/killedbygoogle#1330] opened 2022-12-28 06:25 UTC
**What's the Product's Name?**

YouTube for Nintendo Wii

**Describe the product in a single sentence.**

The YouTube service ported to the Nintendo Wii.

**When was the product launched? Provide a specific date, if possible.**

I can't specifically tell right now, but I think it was 2006, November 19th

**When was the product discontinued? Provide a specific date, if possible.**

2017, June 18th

**What type of product was it? App, Service, or Hardware?**

Service. 

Source: https://en-americas-support.nintendo.com/app/answers/detail/a_id/26400/~/youtube-for-wii-service-has-ended

**Comment by codyogden** [comment] 2022-12-28 06:27
Duplicate of #1317

**Comment by seanpm2001** [comment] 2022-12-28 06:27
This isn't a duplicate though, there is a difference between YouTube for the Wii and the Wii U. They are both different consoles.

**Closed by codyogden** 2022-12-28 06:27 UTC

**Comment by ExperiencersInternational** [comment] 2023-01-26 14:31
> This isn't a duplicate though, there is a difference between YouTube for the Wii and the Wii U. They are both different consoles.
> 
> From the source repository:
> 
> > ** N/A **When was the product discontinued? Provide a specific date, if possible.** October 27th 2022
> 
> YouTube for the Wii U was discontinued 5 whole years later. The Wii and Wii U are different consoles, and it should be noted. Please consider reopening this issue.

Yep, completely different consoles.

Didn't realise someone had mentioned my bug report for something about the Wii.

I think only the 3DS YouTube app closure is mentioned on the site if I'm not wrong?
